[versions]
java = "21"
kotlin = "2.1.21"
moddev = "2.0.99"
loom = "1.10-SNAPSHOT"
dokka = "1.9.20"

minecraft = "1.21.8"
minecraftRange = "[1.21.8, 1.22)"

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment = "2025.07.20"
parchmentMC = "1.21.8"

neoforge = "21.8.25"
neoforgeRange = "[21.8, 21.9)"
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neoForm = "1.21.8-20250717.133445"
kff = "5.9.0"
kffRange = "[5.9, )"

fabricLoader = "0.16.14"
fabricApi = "0.130.0+1.21.8"
flk = "1.13.4+kotlin.2.2.0"

mixin = "0.8.5"
mixinExtras = "0.3.5"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
flk = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "flk" }
kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "fabric-loom", version.ref = "loom" }